### ISSUE TITLE
incorrect result with field named __0

### ISSUE THREAD

**Issue by tromey** [tromey/gdb#25]
I think if a struct has a field named "__0" then "print x.0" will work even though it should not.  This is just a side effect of the implementation.

**Comment by Manishearth** [comment]
This will no longer work, can be closed.

If a struct only has fields named `__%d` its still a problem though. Does dwarf let us arbitrarily tag types with extra metadata?

**Comment by tromey** [comment]
Yes, DWARF does, in a way.  You can add a DWARF attribute.  The attributes are predefined, so we'll need to file a DWARF issue; but in the meantime Rust could stake out some of the vendor space.  It's simplest if this is done by avoiding the existing GCC and LLVM extensions.

I filed this already: https://github.com/rust-lang/rust/issues/32918 and https://github.com/rust-lang/rust/issues/32920
