### ISSUE TITLE
ptype vec bracket parsing error

### ISSUE THREAD

**Issue by m4b** [tromey/gdb#35]
`ptype collections::vec::Vec<u8>` errors with syntax error near `\<u8\>`.

**Comment by tromey** [comment]
I think you need `...::Vec::<u8>` because it is being parsed as an expression.

Though arguably perhaps on parse failure, gdb should try to re-parse as a type rather than an expression.

**Comment by m4b** [comment]
Ah yes, that works, I was just using what gdb autocompleted, so kind of a gotcha, or at the very least an annoyance.

Is this fixable, or not worth the trouble?

**Comment by tromey** [comment]
It does seem confusing and irritating.  So I'd like to fix it if it's possible.

I think the main issue is that it needs context-dependent completion.  We might see a symbol in an expression context or in a type context (like `ptype mumble as vec::Vec<u8>`).

Right now I don't think gdb has a facility for this, so we'd have to add it.

**Comment by tromey** [comment]
Moving this upstream: https://sourceware.org/bugzilla/show_bug.cgi?id=20165

**Comment by m4b** [comment]
:+1:
