### ISSUE TITLE
printing an enum value is ugly

### ISSUE THREAD

**Issue by tromey** [tromey/gdb#7]
Printing an enum value should work nicely without requiring a pretty-printer

**Comment by Manishearth** [comment]
I'm working on this; got a mostly-hackish but working solution. Almost.

**Comment by Manishearth** [comment]
I think this may need changes to rustc to work well, since currently the discriminant is named slightly differently from the field type:

```
{core::option::None {RUST$ENUM$DISR: core::option::Option::Some}, 
  core::option::Some {RUST$ENUM$DISR: core::option::Option::Some, __0: 100}}
```

note `core::option::Some` vs `core::option::Option::Some`.

**Comment by tromey** [comment]
Please note that since I want to send this upstream, if you write a patch then you will have to get copyright assignment papers with the FSF.  I can send you the info you need, contact me by email.

**Comment by tromey** [comment]
The naming discrepancy may come because the enums are marked `DW_AT_enum_class`, which affects the name that gdb gives the enumerator constant.

FWIW I filed a rustc bug about this area because gdb doesn't nicely handle having an enum and a union with the same tag name in the same scope.  You can see the failure mode with `ptype typename` -- it will generally find the enum but not the union, and you really want the latter.

I've also been thinking that it's unfortunate that the expression language doesn't have a way to destructure enums.  Rust does this with `match` but I didn't add that to gdb... seems like a lot of work.

**Comment by Manishearth** [comment]
>  if you write a patch then you will have to get copyright assignment papers with the FSF. I can send you the info you need, contact me by email.

Are these something I can scan and send? If so, no problem, email me at manishearth@gmail. I'm also open to just releasing the patch with a super-permissive license that lets you incorporate it however.

> FWIW I filed a rustc bug about this area because gdb doesn't nicely handle having an enum and a union with the same tag name in the same scope.

Yeah, beginning to realize what's going on here.

**Comment by Manishearth** [comment]
WIP [here](https://github.com/tromey/gdb/compare/rust...Manishearth:rust-enum?expand=1). Let me know if there's something I can improve on there.

In the meantime I'll try to fix the subexpr stuff

**Comment by Manishearth** [comment]
WIP updated with support for subexpressions (tuple-like variants only. I'll have a look at struct variants later).

I have to add some more error handling, sanity checks, and figure out how the testsuite works, but otherwise it seems to work! Comments welcome!

**Comment by tromey** [comment]
A few generic comments.
- gdb is pretty strict about formatting.  Let's not worry about that too much though, I can do a pass to clean it up.  Unless you really want to learn the arcana of GNU styling.
- Instead of rust_extract_field_number perhaps we need to add our own tuple-like structop-struct operator that just passes along an int.  That's another evil gdbism, ugh.
- If a `disr.name` must be freed by the user then you will need to install a cleanup to do so.  gdb uses an exception system (i.e., `error` is `noreturn`) and a cleanup is basically a destructor.  https://sourceware.org/gdb/wiki/Internals%20Cleanups .  Relatedly, gdb uses a wrapper named `xfree`, not `free`.
- `rust_last_path_segment` can be rewritten in terms of some `cp_` functions, I think.  Or we can roll our own.  but anyway look for `cp_find_first_component` in rust-exp.y

**Comment by Manishearth** [comment]
Sounds good. I'll have a look at the style guide but it seems extensive, so help appreciated!

> Instead of rust_extract_field_number perhaps we need to add our own tuple-like structop-struct operator that just passes along an int

I'll try to do that. Note that we still need to support regular-structop for struct variants (though I might work on those last since basically nobody uses them except for a few places in rustc itself).

> rust_last_path_segment can be rewritten in terms of some cp_ functions, I think. Or we can roll our own. but anyway look for cp_find_first_component in rust-exp.y

Rolling my own sounds unnecessary since rust_last_path_segment will always work here (the variant itself cannot contain generics, so it's just the last :: segment). We could just call cp_find_first_component in a loop like strtok and stop when it can't find a component anymore.

Rust debuginfo paths can contain ticks because of lifetimes (or at least they used to) so the same parser may not work, however. I'll keep this as-is for now and look into improving it once everything else is done

**Comment by Manishearth** [comment]
Added structop_anonymous (this breaks tuple structs, will fix along with struct variants since the code will get shared)

**Comment by tromey** [comment]
> Rolling my own sounds unnecessary since rust_last_path_segment will always work here (the variant itself cannot contain generics, so it's just the last :: segment)

Good point, sounds reasonable.

**Comment by Manishearth** [comment]
Does Rust emit any kind of static field info? I'm using NFIELDS in a couple of places and realized it includes static fields too. But that's not a concept that Rust supports.

**Comment by tromey** [comment]
So far I've been ignoring both static fields and base classes.

One oddity in gdb is that a language's value- or type-printer won't necessarily only see values or types arising from that language.  The user can save any value in the value history, switch languages, and print it again.  So ideally the code should be able to deal with anything.

One possible solution to this is to notice unusual objects and just pass them on to the C printers.  Probably just ignoring them is wrong, at least in the way I've done it so far (i.e. pretending they dont' exist)

**Comment by Manishearth** [comment]
Ah, okay. I'll add some code to skip static fields, then.

By the way, how do I set the `show` nesting option for ptype?

Also, is there any way to run just the rust tests?

**Comment by Manishearth** [comment]
Nvm, figured the testing part

**Comment by Manishearth** [comment]
Are you running a special copy of Rust? I get these test failures:

```
FAIL: gdb.rust/simple.exp: print j
FAIL: gdb.rust/simple.exp: ptype j (pattern 1)
FAIL: gdb.rust/simple.exp: print simple::Unit
FAIL: gdb.rust/simple.exp: print z
FAIL: gdb.rust/simple.exp: ptype z (pattern 1)
FAIL: gdb.rust/simple.exp: print simple::ByeBob(0xff, 5)
Running /home/manishearth/Mozilla/Git/gdb/gdb/testsuite/gdb.rust/expr.exp ...
Running /home/manishearth/Mozilla/Git/gdb/gdb/testsuite/gdb.rust/methods.exp ...
FAIL: gdb.rust/methods.exp: print x.take()
FAIL: gdb.rust/methods.exp: print *(x.incr())
FAIL: gdb.rust/methods.exp: print *((&mut x).incr())
FAIL: gdb.rust/methods.exp: info functions HasMethods::new
```

**Comment by tromey** [comment]
I'm using rust 1.8 from the Fedora COPR.

**Comment by Manishearth** [comment]
Ah. I'm on 1.10 nightly

**Comment by Manishearth** [comment]
(fetching stable now)

**Comment by tromey** [comment]
Ok, I will try it sometime soon.

**Comment by Manishearth** [comment]
Added tests. PR here: https://github.com/tromey/gdb/pull/28

**Comment by Manishearth** [comment]
(can be closed)

**Comment by tromey** [comment]
Thank you!

**Comment by Manishearth** [comment]
Btw, I haven't gotten a reply on the copyright assignment email yet.
